### ISSUE TITLE
Board issues

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/L6470-AutoDriver#13]
1) I think we may want to go with the "PANASONIC_E" package for C3. "PANASONIC_C" is the current package, and when you compare it to a scaled product image, it looks too small:
![image](https://cloud.githubusercontent.com/assets/601236/5111549/8de73e0e-6fde-11e4-81c1-4d87fa6a96b3.png)

2) Dimension line is 0.010, should be 0.008

3) Would it be beneficial if we pre-populated all of the PTH connectors with the SS? If so, we should move the packages to locking style.

4) Please add test point to 3.3V net

5) JP1 2 3 and 4, and R4 do not have >NAME text object in the package.

6) remove the M.Hord text object on tvalues

7) add dimension measurements onto the measures layer 47

8) The HTSSOP28 packages used on the L6470 needs it's outline silk bumped up to 8 mil. same thing for trimpot (R4)

9) What does the switch do? Can we add any schematic note and/or board silk to be more descriptive than "SWITCH"

10) Can we add some silk boxes around the GND MOTOR pins, and POWER pins to more clearly shot that each pin is doubled up.

11) Can we scoot the 3 way jumper out a bit so the labeling can be more uniform (that is, each label being on each outer side of the jumper) Or just scoot C8 up a bit so the "3.3V" can live directly above jumper.

12) Looks like there are 4 active low pins on the L6470. We should probably get those updated in the symbol to show that.

13) We should probably add some silk to label the trimpot. Maybe just "Trimpot to ADCIN".

**Comment by lewispg228** [comment]
Sorry to have left this linger so long. I'm not sure how it fell off my radar.

I just did some printing and it looks like all the panasonic packages are wrong. But there is a device for the NIC 10X10.5 cap that is correct.

**Comment by mhord** [comment]
The NIC package is the one that's on there; the first round of protos (with the bad cam job) came back looking good.

**Comment by lewispg228** [comment]
Sorry I was looking at the wrong tree. Here's my review of v11 on the qc-rev:

1) Does the frame have the proper CC attribution? (Frame- Letter/Ledger, CC 4.0) [NO]
comment: Needs latest frame to avoid panelization problem regarding copper version

2) Is 'Revised by:' and 'reviser name' included? [YES]
comment: move back into frame box

3) Are dashed grey lines ('info' eagle layer 97) used to clearly separate different areas? [NO]
comment: dashed lines are currently on symbols layer, should be info

4) Is the VCC range clearly labeled? [NO]
comment: needs vcc range in sch

5) Do any parts have unnecessary values (Eagle has autoset the package as the value)? [YES]
comment: SJ3 JP1 JP2

6) Does your 4 layer board include mike hord's special '1' '2' '3' '4' in the copper of each layer? [NO]
comment: this is nice fore gerber verification

7) Are any vias intended to be used as PTH headers (they shouldn't be)? [YES]
comment: The CSN via should be an actual M01 device

8) Is there a correct version number in the copper? [NO]
comment: copper version is outside dimension of board

9) Are measurements included for outer dimension and standoffs (Eagle layer 47)? [NO]
comment: needs measures

**Comment by mhord** [comment]
Killer. I'll make these changes along with anything we find out from this round of re-cammed protos.

**Comment by lewispg228** [comment]
Thanks Mike. 

I think production (Nick Harmier or Austin Metzger) is waiting for us to finalize this review before they re-cam it up and order another round of protos. 

They won't order any protos until they see (1) uploaded complete review Excell doc and (2) the review flag set to "+".

**Comment by mhord** [comment]
Fixed.
