### ISSUE TITLE
Conversion Values for ACC and DEC Registers

### ISSUE THREAD

**Issue by MeijinGandalf** [sparkfun/L6470-AutoDriver#25]
in accCalc you are using the value 0.137438 to convert to the proper register value. The equation is 

[step/s^2] = ACC *2^-40/tick^2 where tick = 250ns
 
so

ACC = [step/s^2]*tick^2/2^-40 and 
tick^2/2^-40 = .0687. This is the value that I think should be used to convert from [step/s] to ACC and DEC.

**Comment by mhord** [comment]
The Autodriver library is about to undergo a major overhaul; I'll include this fix when that happens. Thanks!
