### ISSUE TITLE
hardHiZ does not put motor in High-Impedance mode

### ISSUE THREAD

**Issue by alborzs** [sparkfun/L6470-AutoDriver#27]
calling `hardHiZ()` in `v13` of this library does NOT put the motor in high-impedance mode.
I have looked at the code to find the issue but I have not been successful yet.
What does work and put the motor in high-impedance mode is `hardStop()`.
You are welcome to test this for yourself.

**Comment by mhord** [comment]
Th;is is not consistent with my observations. hardStop() hard stops the board, putting the board in Hold mode so that the shaft resists being turned. hardHiZ() puts the board into HiZ mode, where there is no load on the coils, allowing the shaft to spin more or less freely.
