### ISSUE TITLE
Mechanical drawing

### ISSUE THREAD

**Issue by MarcusWolschon** [sparkfun/L6470-AutoDriver#28]
A simple mechanical drawing that provides the location of the mounting holes and the board dimensions would be very nice.
Not everyone has EAGLE or knows how to use it to get a DXF these from the .brd file.

**Comment by mhord** [comment]
We've (globally) elected not to do this since there is a free version of Eagle available and we include measurements in the board design files. We realize that it doesn't work for everyone, but neither will dxf, svg, or any other format we choose. Eagle is simply the least common denominator.

**Comment by MarcusWolschon** [comment]
So for non-personal or commercial use the user is expected to buy Eagle or take their own meassurements? This is rediculus.

**Comment by mhord** [comment]
![autodriver_dimensions](https://cloud.githubusercontent.com/assets/1335086/22900422/872fac2c-f1eb-11e6-86c3-870ab04a2fc4.png)

Here's a PNG of the mechanical layout. You bring up an interesting point regarding licensing of EAGLE. I'll bring the topic up for debate again.
