### ISSUE TITLE
SparkFun Fritzing repo - Fritzing diagrams for SparkFun products.

### ISSUE THREAD

**Issue by MarcusWolschon** [sparkfun/L6470-AutoDriver#31]
In README.md you mention the "SparkFun Fritzing repo" but that one doesn't seem to contain the L6470-Autodrive board in "products"

**Comment by loricrotser** [comment]
Just checked in the fritzing part for v13. v10 should be uploaded sometime in the next week. 
[https://github.com/sparkfun/Fritzing_Parts/blob/master/products/13752_sfe_autodriver_stepper_motor_v13.fzpz](https://github.com/sparkfun/Fritzing_Parts/blob/master/products/13752_sfe_autodriver_stepper_motor_v13.fzpz)
