### ISSUE TITLE
Hi! How does one change the ‘SDO to:’ jumper setting to ‘Next bd’ on the Autodriver v13 board? Thank you!

### ISSUE THREAD

**Issue by holstenholsten** [sparkfun/L6470-AutoDriver#33]

**Comment by mhord** [comment]
You'll need some desoldering wick to remove the solder that's present on the jumper, then to solder the two pads on the "Next bd" side of the jumper.

**Comment by holstenholsten** [comment]
Thank you for the quick reply. Should I do this on both boards, or just the first one?

**Comment by mhord** [comment]
The first board in the series only.
