### ISSUE TITLE
Support for the Arduino Due

### ISSUE THREAD

**Issue by einspunktnull** [sparkfun/L6470-AutoDriver#9]
Hey again,

I wan't to use the lib with Arduino Due. But because of the different architecture of the Due your lib is not working. Can you make that working, please?

Best, Albrecht

**Comment by cinetics** [comment]
Hey, it seems like this driver will not compile on Version 1.6.8 but only on version 1.5.8. 

Do you happen to know the fix for this? 

Thank you,
